#!/bin/bash

[ -z $1 ] && echo "No configuration provided" && exit 0
[ -d $1 ] || echo "Could not find directory $1" || exit 0
echo "Cofiguration provided from $1"

echo "Your current config will be lost! Confirm? [y|n]"
read confirm && [[ $confirm == [Yy] ]] || exit 0 || unset 'confirm'

echo "Deleting existing included directories..."
for included in $(sed 's#~#'$HOME'#g' $1/included); do
    sudo rm -rf $included -v
    noprefix=${included#$HOME}
    [[ $included == $HOME* ]] && ln -s -v "$1/home$noprefix" "$included" || sudo ln -s -v "$1/root$noprefix" "$included"
done
