#!/bin/bash

[ -z $1 ] && echo "No configuration provided" && exit 0
[ -d $1 ] || echo "Could not find directory $1" || exit 0
echo "Cofiguration provided from $1"

[[ -z $(pacman -Q paru) ]] && echo "paru is not installed, installing paru..." && ( git clone https://aur.archlinux.org/paru.git; cd paru; makepkg -si)

echo "Updating system..."
paru -Syu

for package in $(cat $1/packages); do
    paru -S $package --noconfirm
done
